version: '3.8'

services:
        myblog:
                build: .
                image: blog_local:latest
                container_name: My_blog
                restart: always
                volumes:
                        - /home/lonelyhorse/work/My_blog/notes:/usr/local/My_blog/notes
                        - /home/lonelyhorse/work/My_blog/posts:/usr/local/My_blog/posts
                        - /home/lonelyhorse/work/My_blog/static/projects:/usr/local/My_blog/static/projects
                        - /home/lonelyhorse/work/My_blog/projects_web/projects.json:/usr/local/My_blog/projects.json
                environment:
                        - TZ=Asia/Shanghai
                network_mode: host
